name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "epfhhqy4tuyhw9xv0tjvm0ns"
  title = "Add blog article about chesslab"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "atmcyivqbhorjv8cizumxgp1"
  title = "Add blog article about The sun never sleep"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ea8loqd6uuubiztmg9dtwltg"
  title = "Fix/Improve SVG"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "vwb16xrga6pzy57rgud54tmy"
name = "Priority"

  [[processes.tasks]]
  id = "rsgpkc7nvlboid02qq4nt54q"
  title = "Update Portfolio"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "rlmtir8dyslu1hxyjvs6bl82"
  title = "Remove all console error and warning"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "gij445t8bdqsxdnz422roh0c"
  title = "Fix/Improve Routing"
  description = "<p>Things should not reload when changing pages<br>Also merge layout components maybe ?</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "gwl1wytycwfor283sur1lcrg"
  title = "Update CV"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "e6lflhk0jhd0j4q6wsoawd9h"
  title = "Remove useless: Backend, DB, JWT, axios, jest, tetris, minesweaper"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "v6e9657rdh03wyxvjoiv9g5h"
  title = "Move from yarn to pnpm"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ykvzp1rxm2vyzb8ujwzooda8"
  title = "Test website localy"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ztoj13a15k11lmluyykoi166"
  title = "Update documentation"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "e84838ed74r01g8yyadet4u5"
  title = "Upgrade all packages"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ouf40c0ssiuw6dwcyqhlyc61"
  title = "Deploy to Github Pages"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ab3mee0bbazkg0l3wk7xpgbu"
  title = "Change domain name to uspec.click"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "hqo91kxk1fbyeoy2i4zt06ho"
  title = "Run modern lint and format"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "onha36x1l9psbhk90hdin9i8"
  title = "Convert mantine to pure css files"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "e4mq3ohfqumuhu9zf7e2ysr8"
  title = "Fix/Improve images "
  description = "also resize documentation or suppression"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "rzw60zy57ewzwcht7cow5x4o"
  title = "Update achitecture"
  description = "<p>by running create app from scratch<br>this also fixes build issues</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "w4avgnv493gyzbrc0z3y8oc7"
  title = "Improve Home page"
  description = """
- make portfoliot note go out
- fix the width of the pictures and the text"""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "eam81kibn8grrg1otshg8zgh"
  title = "Fix/Improve i18n"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
