name: Deploy staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [staging]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Load npm cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules
      - name: Dependencies installation
        run: npm install
      - name: Add env variables
        run: |
          echo "    DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}" >> .ebextensions/options.config
          echo "    NODE_ENV: staging" >> .ebextensions/options.config
      - name: Prisma generate
        run: npx prisma generate
      - name: database migration
        run: npx prisma migrate deploy
      - name: Generate build
        run: npx nx build backend --prod
      - name: Pick Procfile
        run: mv Procfile_Backend Procfile
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        env:
          VERSION_LABEL: uspec-backend-staging-${{ github.run_number }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: staging-backend
          environment_name: staging-backend
          version_label: ${{ env.VERSION_LABEL }}
          region: eu-west-3
          deployment_package: deploy.zip

  frontend:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_NODE_ENV: staging
      NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Load npm cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules
      - name: Dependencies installation
        run: npm install
      - name: Add env variables
        run: |
          echo "    NEXT_PUBLIC_NODE_ENV: staging" >> .ebextensions/options.config
          echo "    NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}" >> .ebextensions/options.config
      - name: Generate build
        run: npx nx build frontend --prod
      - name: Pick Procfile
        run: mv Procfile_Frontend ./dist/apps/frontend/Procfile
      - name: Generate deployment package
        run: cd dist/apps/frontend && zip -r deployfrontend.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        env:
          VERSION_LABEL: uspec-frontend-staging-${{ github.run_number }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: staging-frontend
          environment_name: staging-frontend
          version_label: ${{ env.VERSION_LABEL }}
          region: eu-west-3
          deployment_package: dist/apps/frontend/deployfrontend.zip
